version: '2.3'

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/upstream.conf:/etc/nginx/upstream.conf
      - ./nginx/logs/host.access.log:/etc/nginx/logs/host.access.log