version: '2.3'

services:
  redis:
    image: redis:5.0.9
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server --dir /data
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf